CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL,
    game_id VARCHAR(64) NOT NULL,
    discord VARCHAR
);

CREATE TABLE beta_users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL,
    game_id VARCHAR(64) NOT NULL,
    discord VARCHAR
);
